"""
Notifications Module

Send recommendations via Email (Resend).
"""

import os

import httpx
from pydantic import BaseModel

from src.web_search import AlbumInfo


class NotificationResult(BaseModel):
    """Result of a notification attempt"""

    success: bool
    message: str | None = None
    error: str | None = None


def format_recommendations_markdown(
    recommendations: list[AlbumInfo],
    title: str = "🎵 Your Music Recommendations",
) -> str:
    """Format recommendations as Markdown for messaging"""

    lines = [f"*{title}*", ""]

    for i, album in enumerate(recommendations, 1):
        lines.append(f"*{i}. {album.title}* by _{album.artist}_")

        if album.genre:
            lines.append(f"   🎸 Genre: {album.genre}")
        if album.release_date:
            lines.append(f"   📅 Released: {album.release_date}")
        if album.why_recommended:
            lines.append(f"   💡 {album.why_recommended}")
        lines.append("")

    return "\n".join(lines)


def format_recommendations_html(
    recommendations: list[AlbumInfo],
    title: str = "🎵 Your Music Recommendations",
) -> str:
    """Format recommendations as HTML for email"""

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 600px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1DB954; }}
        .album {{ background: #f5f5f5; padding: 15px; margin: 10px 0; border-radius: 8px; }}
        .album-title {{ font-size: 18px; font-weight: bold; color: #333; }}
        .album-artist {{ color: #666; font-style: italic; }}
        .album-meta {{ color: #888; font-size: 14px; margin-top: 8px; }}
        .album-why {{ color: #1DB954; font-size: 14px; margin-top: 8px; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
"""

    for album in recommendations:
        html += f"""
    <div class="album">
        <div class="album-title">{album.title}</div>
        <div class="album-artist">by {album.artist}</div>
        <div class="album-meta">
            {f"🎸 {album.genre}" if album.genre else ""}
            {f" • 📅 {album.release_date}" if album.release_date else ""}
        </div>
        {f'<div class="album-why">💡 {album.why_recommended}</div>' if album.why_recommended else ""}
    </div>
"""

    html += """
    <p style="color: #888; font-size: 12px; margin-top: 30px;">
        Generated by your Music Recommendation Agent 🤖
    </p>
</body>
</html>
"""
    return html


class EmailNotifier:
    """Send notifications via Resend email API"""

    def __init__(self, api_key: str, from_email: str):
        self.api_key = api_key
        self.from_email = from_email
        self.api_url = "https://api.resend.com/emails"

    def send_email(
        self,
        to: str,
        subject: str,
        html: str,
    ) -> NotificationResult:
        """Send an email"""
        try:
            with httpx.Client() as client:
                response = client.post(
                    self.api_url,
                    headers={
                        "Authorization": f"Bearer {self.api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "from": self.from_email,
                        "to": [to],
                        "subject": subject,
                        "html": html,
                    },
                )
                response.raise_for_status()

                return NotificationResult(
                    success=True,
                    message=f"Email sent to {to}",
                )

        except Exception as e:
            return NotificationResult(
                success=False,
                error=str(e),
            )

    def send_recommendations(
        self,
        recommendations: list[AlbumInfo],
        to_email: str,
        title: str = "🎵 Your Music Recommendations",
    ) -> NotificationResult:
        """Send formatted recommendations via email"""
        html = format_recommendations_html(recommendations, title)
        return self.send_email(
            to=to_email,
            subject=title,
            html=html,
        )


class NotificationService:
    """
    Notification service - sends recommendations via email (Resend).
    """

    def __init__(self):
        self.email: EmailNotifier | None = None

        resend_api_key = os.getenv("RESEND_API_KEY")
        resend_from_email = os.getenv("RESEND_FROM_EMAIL")
        if resend_api_key and resend_from_email:
            self.email = EmailNotifier(
                api_key=resend_api_key,
                from_email=resend_from_email,
            )

    def send_recommendations(
        self,
        recommendations: list[AlbumInfo],
        title: str = "🎵 Your Music Recommendations",
        email_to: str | None = None,
    ) -> NotificationResult | None:
        """
        Send recommendations via email.

        Args:
            recommendations: List of albums to recommend
            title: Title for the notification
            email_to: Email address for email notifications
        """
        if not self.email:
            print("❌ Email not configured (missing RESEND_API_KEY or RESEND_FROM_EMAIL)")
            return None

        to_email = email_to or os.getenv("EMAIL_TO")
        if not to_email:
            print("❌ No recipient email configured (missing EMAIL_TO)")
            return None

        print(f"📧 Sending to {to_email}...")
        result = self.email.send_recommendations(
            recommendations,
            to_email=to_email,
            title=title,
        )
        if result.success:
            print("   ✅ Email sent!")
        else:
            print(f"   ❌ Email failed: {result.error}")

        return result


# Quick test
def quick_test():
    """Test notification formatting"""
    test_albums = [
        AlbumInfo(
            title="Test Album",
            artist="Test Artist",
            genre="Indie Rock",
            release_date="January 2025",
            why_recommended="Based on your love of indie music",
        ),
        AlbumInfo(
            title="Another Album",
            artist="Another Artist",
            genre="Electronic",
            why_recommended="Matches your electronic taste",
        ),
    ]

    print("Markdown format:")
    print("-" * 40)
    print(format_recommendations_markdown(test_albums))

    print("\n\nHTML format:")
    print("-" * 40)
    print(format_recommendations_html(test_albums))


if __name__ == "__main__":
    quick_test()
